# Generated by Django 2.0.4 on 2018-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_exhibits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exhibits',
            new_name='Exhibit',
        ),
    ]
