# Generated by Django 2.0.4 on 2018-04-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_auto_20180425_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to=None)),
                ('sound', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('political', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='hasExit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='fromExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Exhibit'),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='toExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbor_of', to='zoo.Exhibit'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Animal'),
        ),
    ]
