# Generated by Django 2.0.4 on 2018-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_auto_20180425_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='logoFileName',
            field=models.CharField(help_text='Enter a url.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
