# Generated by Django 2.0.4 on 2018-05-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_auto_20180430_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='animal',
        ),
        migrations.AddField(
            model_name='animal',
            name='exhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Exhibit'),
        ),
    ]
