# Generated by Django 2.0.4 on 2018-05-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_auto_20180501_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='direction',
            field=models.CharField(blank=True, choices=[('n', 'North'), ('s', 'South'), ('w', 'West'), ('e', 'East'), ('ne', 'Northeast'), ('nw', 'Northwest'), ('se', 'Southeast'), ('sw', 'Southwest')], help_text='Enter direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='fromExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromExhibit', to='zoo.Exhibit'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='toExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toExhibit', to='zoo.Exhibit'),
        ),
    ]
