# Generated by Django 2.0.4 on 2018-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_auto_20180501_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.AddField(
            model_name='animal',
            name='imageFileName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
